# http://about.travis-ci.org/docs/user/selenium-setup/
rvm:
  - 1.9.2
before_script:
  - "mv config/database.travis.yml config/database.yml"
#  - sh -e /etc/init.d/xvfb start
script: "bundle exec rake db:setup &&  bundle exec rake spec"
branches:
  only:
    - master
notifications:
  recipients:
    - tobi@rngtng.com
