#!/usr/bin/env ruby

require "rubygems"
require "bundler/setup"
Bundler.require(:client)

require "net/http"
require "optparse"

require_relative "../lib/pin_pirate_client"

@port       = "/dev/tty.usbserial-A7006Qaq"
@client_env = :production
@baud_rate  = 115200

OptionParser.new do |opts|
  opts.banner = "Usage: script/client [options] [port]"
  opts.on("-e",  "--env=CLIENT_ENV", "Client Environment (production/development)") { |env| @client_env = env.to_sym }
  opts.on("-d",  "--development", "Set Client Environment to development") { |env| @client_env = :development }
  opts.on("-b",  "--baud=BAUD_RATE", "Baud Rate") { |baud| @baud_rate = baud.to_i }
end.parse!

@port = ARGV.first if ARGV.any?

puts "Listening on port #{@port} at #{@baud_rate}, posting to #{@client_env}"

@client = PinPirateClient.new

SerialPort.open(@port, @baud_rate) do |sp|
  sp.each_line do |line|
    begin
      data = @client.process(*line.strip.split(","))
      puts data.inspect if data
    rescue => e
      puts e.message
    end
  end
end
